# Generated by Django 4.1.3 on 2022-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=45, verbose_name='nome')),
                ('descicaoProduto', models.CharField(max_length=90, verbose_name='descricao')),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('categoriaProduto', models.CharField(max_length=1, verbose_name='categoria')),
            ],
        ),
    ]
