# Generated by Django 4.1.3 on 2022-12-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(max_length=50, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMesa', models.IntegerField(verbose_name='numeroMesa')),
                ('statusMesa', models.CharField(max_length=2, verbose_name='statusMesa')),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('senha', models.CharField(max_length=8, verbose_name='senha')),
                ('telefone', models.BigIntegerField(verbose_name='telefone')),
                ('tipo', models.CharField(max_length=1, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=45, verbose_name='nome')),
                ('descricaoProduto', models.CharField(max_length=90, verbose_name='descricao')),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedido', models.TimeField(verbose_name='dataHoraPedido')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.mesa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPagamento', models.CharField(max_length=1, verbose_name='formaPagamento')),
                ('dataPagamento', models.DateField(verbose_name='dataPagamento')),
                ('valorPagamento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valorPagamento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.mesa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pedido')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.produto')),
            ],
        ),
        migrations.CreateModel(
            name='itemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorItemPedido', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valorItemPedido')),
                ('quantidadeItemPedido', models.IntegerField(verbose_name='quantidadeItemPedido')),
                ('statusItem', models.CharField(max_length=5, verbose_name='statusItemPedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pedido')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.produto')),
            ],
        ),
    ]
