# Generated by Django 4.1.3 on 2022-12-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='porcentagemPedido',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=8, verbose_name='porcentagemPedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='valorPedido',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=8, verbose_name='valorPedido'),
            preserve_default=False,
        ),
    ]
