# Generated by Django 4.1.3 on 2022-11-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMesa', models.IntegerField(max_length=4, verbose_name='numeroMesa')),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('senha', models.CharField(max_length=8, verbose_name='senha')),
                ('telefone', models.BigIntegerField(max_length=9, verbose_name='telefone')),
                ('tipo', models.CharField(max_length=1, verbose_name='tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoriaProduto',
            field=models.CharField(max_length=50, verbose_name='categoria'),
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedido', models.DateField(verbose_name='dataPedido')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.mesa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.produto')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPagamento', models.CharField(max_length=1, verbose_name='formaPagamento')),
                ('dataPagamento', models.DateField(verbose_name='dataPagamento')),
                ('valorPagamento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valorPagamento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.mesa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pedido')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.produto')),
            ],
        ),
        migrations.CreateModel(
            name='itemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorItemPedido', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valorItemPedido')),
                ('quantidadeItemPedido', models.IntegerField(max_length=2, verbose_name='quantidadeItemPedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pedido')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.produto')),
            ],
        ),
    ]
