# Generated by Django 4.1.3 on 2022-11-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_mesa_pessoa_alter_produto_categoriaproduto_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='quantidadeItemPedido',
            field=models.IntegerField(verbose_name='quantidadeItemPedido'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numeroMesa',
            field=models.IntegerField(verbose_name='numeroMesa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.BigIntegerField(verbose_name='telefone'),
        ),
    ]
