# Generated by Django 4.1.3 on 2022-12-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_pedido_porcentagempedido_pedido_valorpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='sistema.mesa'),
        ),
    ]
