# Generated by Django 4.1.3 on 2022-12-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subTotalPedido',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8, verbose_name='subTotalPedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.mesa'),
        ),
    ]
