# Generated by Django 4.1.3 on 2022-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_itempedido_quantidadeitempedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='statusItem',
            field=models.CharField(default=0, max_length=5, verbose_name='statusItemPedido'),
            preserve_default=False,
        ),
    ]
