# Generated by Django 4.1.3 on 2022-12-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_pedido_subtotalpedido_alter_pedido_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='produto',
        ),
    ]
