# Generated by Django 4.1.3 on 2022-12-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_itempedido_statusitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='statusMesa',
            field=models.CharField(default='a', max_length=2, verbose_name='statusMesa'),
            preserve_default=False,
        ),
    ]
