# Generated by Django 4.1.3 on 2022-12-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_remove_pagamento_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='formaPagamento',
            field=models.CharField(max_length=9, verbose_name='formaPagamento'),
        ),
    ]
