# Generated by Django 4.1.3 on 2022-12-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_mesa_statusmesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateTimeField(verbose_name='dataHoraPedido'),
        ),
    ]
