# Generated by Django 4.1.3 on 2022-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_remove_pedido_produto_alter_pedido_datapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.TimeField(verbose_name='dataHoraPedido'),
        ),
    ]
