# Generated by Django 4.1.3 on 2022-12-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_pagamento_formapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='dataPagamento',
            field=models.DateTimeField(verbose_name='dataPagamento'),
        ),
    ]
