# Generated by Django 4.1.3 on 2022-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_pagamento_datapagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='valorPagamentoServico',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=8, verbose_name='valorPagamentoServico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valorPagamentoSubTotal',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=8, verbose_name='valorPagamentoSubTotal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='nome'),
        ),
    ]
